// Copyright 2014
// If you read this file you should have read and been given a copy of the closed license concerning HRP2
//

// This file has been generated by the metapod robotbuilder library.

#ifndef METAPOD_HRP2_14_INIT_HH
# define METAPOD_HRP2_14_INIT_HH

# ifdef _MSC_VER
#  pragma warning( push )
// disable warning C4251: need to have DLL interface
// disable warning C4099: struct/class discrepancies
// The following warnings are only needed if the FloatType is float, because
// the code generator uses double anyway.
// disable warning C4305 truncation from 'double' to 'float'
// disable warning C4244 conversion from 'double' to 'float', possible loss of data
#  pragma warning( disable: 4251 4099 4305 4244 )
# endif

# include "config.hh"

# include <metapod/tools/common.hh>
# include <metapod/tools/joint.hh>
# include <metapod/tools/initnufwddyn.hh>

// by default, boost fusion vector only provides constructor for vectors with
// up to 10 elements.
# if !defined(FUSION_MAX_VECTOR_SIZE) && (31 > 10)
#  define FUSION_MAX_VECTOR_SIZE 31
# endif
# if defined(FUSION_MAX_VECTOR_SIZE) && (31 > FUSION_MAX_VECTOR_SIZE)
// todo: warn or stop
# endif
# include <boost/fusion/sequence.hpp>
# include <boost/fusion/include/sequence.hpp>
# include <boost/fusion/include/vector.hpp>

namespace metapod {

template <typename FloatType>
class METAPOD_HRP2_14_DLLAPI hrp2_14 {
  METAPOD_TYPEDEFS;
public:
  // the following new/delete operators are only needed if there is a
  // member variable of fixed-size vectorizable Eigen type (or a member
  // having such a member).
  // It's not easy to tell in advance, so let always use the aligned operators.
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  // Global constants or variable of the robot
  enum { NBDOF = 36 };
  enum { NBBODIES = 31 };

  typedef FloatType RobotFloatType;
  typedef Eigen::Matrix< FloatType, NBDOF, 1 > confVector;

  enum NodeId
  {
    BODY = 0,
    RLEG_LINK0 = 1,
    RLEG_LINK1 = 2,
    RLEG_LINK2 = 3,
    RLEG_LINK3 = 4,
    RLEG_LINK4 = 5,
    r_ankle = 6,
    LLEG_LINK0 = 7,
    LLEG_LINK1 = 8,
    LLEG_LINK2 = 9,
    LLEG_LINK3 = 10,
    LLEG_LINK4 = 11,
    l_ankle = 12,
    CHEST_LINK0 = 13,
    torso = 14,
    HEAD_LINK0 = 15,
    HEAD_LINK1 = 16,
    RARM_LINK0 = 17,
    RARM_LINK1 = 18,
    RARM_LINK2 = 19,
    RARM_LINK3 = 20,
    RARM_LINK4 = 21,
    r_wrist = 22,
    RARM_LINK6 = 23,
    LARM_LINK0 = 24,
    LARM_LINK1 = 25,
    LARM_LINK2 = 26,
    LARM_LINK3 = 27,
    LARM_LINK4 = 28,
    l_wrist = 29,
    LARM_LINK6 = 30
  };

  // children of the root/NP node
  static const int child0_id = 0;
  static const int child1_id = -2;
  static const int child2_id = -2;
  static const int child3_id = -2;
  static const int child4_id = -2;

  // definition of the node classes (except the root/NP node)

  class METAPOD_HRP2_14_DLLAPI Node0 {
  public:
    Node0();
    static const int id = 0;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node0 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 0;
    typedef FreeFlyerJoint<FloatType> Joint;
    static const int parent_id = -1;
    static const int child0_id = 1;
    static const int child1_id = 7;
    static const int child2_id = 13;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node1 {
  public:
    Node1();
    static const int id = 1;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node1 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 6;
    typedef RevoluteAxisZJoint<FloatType> Joint;
    static const int parent_id = 0;
    static const int child0_id = 2;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutZTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node2 {
  public:
    Node2();
    static const int id = 2;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node2 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 7;
    typedef RevoluteAxisXJoint<FloatType> Joint;
    static const int parent_id = 1;
    static const int child0_id = 3;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutXTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node3 {
  public:
    Node3();
    static const int id = 3;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node3 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 8;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 2;
    static const int child0_id = 4;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node4 {
  public:
    Node4();
    static const int id = 4;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node4 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 9;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 3;
    static const int child0_id = 5;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node5 {
  public:
    Node5();
    static const int id = 5;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node5 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 10;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 4;
    static const int child0_id = 6;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node6 {
  public:
    Node6();
    static const int id = 6;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node6 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 11;
    typedef RevoluteAxisXJoint<FloatType> Joint;
    static const int parent_id = 5;
    static const int child0_id = -2;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutXTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node7 {
  public:
    Node7();
    static const int id = 7;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node7 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 12;
    typedef RevoluteAxisZJoint<FloatType> Joint;
    static const int parent_id = 0;
    static const int child0_id = 8;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutZTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node8 {
  public:
    Node8();
    static const int id = 8;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node8 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 13;
    typedef RevoluteAxisXJoint<FloatType> Joint;
    static const int parent_id = 7;
    static const int child0_id = 9;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutXTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node9 {
  public:
    Node9();
    static const int id = 9;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node9 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 14;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 8;
    static const int child0_id = 10;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node10 {
  public:
    Node10();
    static const int id = 10;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node10 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 15;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 9;
    static const int child0_id = 11;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node11 {
  public:
    Node11();
    static const int id = 11;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node11 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 16;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 10;
    static const int child0_id = 12;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node12 {
  public:
    Node12();
    static const int id = 12;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node12 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 17;
    typedef RevoluteAxisXJoint<FloatType> Joint;
    static const int parent_id = 11;
    static const int child0_id = -2;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutXTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node13 {
  public:
    Node13();
    static const int id = 13;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node13 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 18;
    typedef RevoluteAxisZJoint<FloatType> Joint;
    static const int parent_id = 0;
    static const int child0_id = 14;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutZTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node14 {
  public:
    Node14();
    static const int id = 14;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node14 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 19;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 13;
    static const int child0_id = 15;
    static const int child1_id = 17;
    static const int child2_id = 24;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node15 {
  public:
    Node15();
    static const int id = 15;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node15 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 20;
    typedef RevoluteAxisZJoint<FloatType> Joint;
    static const int parent_id = 14;
    static const int child0_id = 16;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutZTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node16 {
  public:
    Node16();
    static const int id = 16;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node16 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 21;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 15;
    static const int child0_id = -2;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node17 {
  public:
    Node17();
    static const int id = 17;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node17 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 22;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 14;
    static const int child0_id = 18;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node18 {
  public:
    Node18();
    static const int id = 18;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node18 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 23;
    typedef RevoluteAxisXJoint<FloatType> Joint;
    static const int parent_id = 17;
    static const int child0_id = 19;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutXTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node19 {
  public:
    Node19();
    static const int id = 19;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node19 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 24;
    typedef RevoluteAxisZJoint<FloatType> Joint;
    static const int parent_id = 18;
    static const int child0_id = 20;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutZTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node20 {
  public:
    Node20();
    static const int id = 20;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node20 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 25;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 19;
    static const int child0_id = 21;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node21 {
  public:
    Node21();
    static const int id = 21;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node21 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 26;
    typedef RevoluteAxisZJoint<FloatType> Joint;
    static const int parent_id = 20;
    static const int child0_id = 22;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutZTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node22 {
  public:
    Node22();
    static const int id = 22;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node22 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 27;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 21;
    static const int child0_id = 23;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node23 {
  public:
    Node23();
    static const int id = 23;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node23 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 28;
    typedef RevoluteAxisXJoint<FloatType> Joint;
    static const int parent_id = 22;
    static const int child0_id = -2;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutXTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node24 {
  public:
    Node24();
    static const int id = 24;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node24 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 29;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 14;
    static const int child0_id = 25;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node25 {
  public:
    Node25();
    static const int id = 25;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node25 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 30;
    typedef RevoluteAxisXJoint<FloatType> Joint;
    static const int parent_id = 24;
    static const int child0_id = 26;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutXTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node26 {
  public:
    Node26();
    static const int id = 26;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node26 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 31;
    typedef RevoluteAxisZJoint<FloatType> Joint;
    static const int parent_id = 25;
    static const int child0_id = 27;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutZTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node27 {
  public:
    Node27();
    static const int id = 27;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node27 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 32;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 26;
    static const int child0_id = 28;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node28 {
  public:
    Node28();
    static const int id = 28;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node28 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 33;
    typedef RevoluteAxisZJoint<FloatType> Joint;
    static const int parent_id = 27;
    static const int child0_id = 29;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutZTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node29 {
  public:
    Node29();
    static const int id = 29;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node29 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 34;
    typedef RevoluteAxisYJoint<FloatType> Joint;
    static const int parent_id = 28;
    static const int child0_id = 30;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixAboutYTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };

  class METAPOD_HRP2_14_DLLAPI Node30 {
  public:
    Node30();
    static const int id = 30;
    static const std::string joint_name;
    static const bool jointFwdDyn = false; // <dynamics> fwd_dyn field, used by chda
    static const bool jointNuOfFwdDyn = initNuFwdDyn< hrp2_14<FloatType>, hrp2_14<FloatType>::Node30 >::value; // subtree supported by at least one fwdDyn joint
    static const std::string body_name;
    static const Spatial::TransformT<FloatType, Spatial::RotationMatrixIdentityTpl<FloatType> > Xt;
    static const int q_idx = 35;
    typedef RevoluteAxisAnyJoint<FloatType> Joint;
    static const int parent_id = 29;
    static const int child0_id = -2;
    static const int child1_id = -2;
    static const int child2_id = -2;
    static const int child3_id = -2;
    static const int child4_id = -2;
    Spatial::TransformT<FloatType, typename Spatial::rm_mul_op<FloatType,Spatial::RotationMatrixTpl<FloatType>, Spatial::RotationMatrixIdentityTpl<FloatType> >::rm> sXp;
    Eigen::Matrix<FloatType, 6, Joint::NBDOF> joint_F; // used by crba
    Joint joint;
    Body<FloatType> body;
  };


  // vector of the robot nodes
  typedef boost::fusion::vector31<
      Node0,
      Node1,
      Node2,
      Node3,
      Node4,
      Node5,
      Node6,
      Node7,
      Node8,
      Node9,
      Node10,
      Node11,
      Node12,
      Node13,
      Node14,
      Node15,
      Node16,
      Node17,
      Node18,
      Node19,
      Node20,
      Node21,
      Node22,
      Node23,
      Node24,
      Node25,
      Node26,
      Node27,
      Node28,
      Node29,
      Node30>
  NodeVector;

  // member variables

  // inertias expressed in body frames
  static Inertia inertias[31];
  NodeVector nodes;
  Eigen::Matrix< FloatType, NBDOF, NBDOF > H; // used by crba
  
  // permutation matrix Q
  typedef Eigen::Matrix<FloatType, 1, NBDOF> VectorNBDOFf;
  typedef Eigen::Matrix<FloatType, NBDOF, NBDOF> MatrixNBDOFf;
  typedef Eigen::PermutationMatrix<NBDOF, NBDOF, FloatType> PermutationMatrixNBDOFf;
  static const int nbFdDOF = 0;
  static VectorNBDOFf fdNodesFirst; // permutation indexes for building Q matrix
  static VectorNBDOFf idNodes; // permutation indexes for building Q matrix
  static int fdNodesFirstFillIndex;
  static int idNodesFillIndex;
  static PermutationMatrixNBDOFf Q;
  static PermutationMatrixNBDOFf Qt; // transpose of Q
  
  hrp2_14():
    H(MatrixNBDOFf::Zero())
  {}
};

// map node id to node type
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 0> {typedef typename hrp2_14<FloatType>::Node0 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 1> {typedef typename hrp2_14<FloatType>::Node1 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 2> {typedef typename hrp2_14<FloatType>::Node2 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 3> {typedef typename hrp2_14<FloatType>::Node3 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 4> {typedef typename hrp2_14<FloatType>::Node4 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 5> {typedef typename hrp2_14<FloatType>::Node5 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 6> {typedef typename hrp2_14<FloatType>::Node6 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 7> {typedef typename hrp2_14<FloatType>::Node7 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 8> {typedef typename hrp2_14<FloatType>::Node8 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 9> {typedef typename hrp2_14<FloatType>::Node9 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 10> {typedef typename hrp2_14<FloatType>::Node10 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 11> {typedef typename hrp2_14<FloatType>::Node11 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 12> {typedef typename hrp2_14<FloatType>::Node12 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 13> {typedef typename hrp2_14<FloatType>::Node13 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 14> {typedef typename hrp2_14<FloatType>::Node14 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 15> {typedef typename hrp2_14<FloatType>::Node15 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 16> {typedef typename hrp2_14<FloatType>::Node16 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 17> {typedef typename hrp2_14<FloatType>::Node17 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 18> {typedef typename hrp2_14<FloatType>::Node18 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 19> {typedef typename hrp2_14<FloatType>::Node19 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 20> {typedef typename hrp2_14<FloatType>::Node20 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 21> {typedef typename hrp2_14<FloatType>::Node21 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 22> {typedef typename hrp2_14<FloatType>::Node22 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 23> {typedef typename hrp2_14<FloatType>::Node23 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 24> {typedef typename hrp2_14<FloatType>::Node24 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 25> {typedef typename hrp2_14<FloatType>::Node25 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 26> {typedef typename hrp2_14<FloatType>::Node26 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 27> {typedef typename hrp2_14<FloatType>::Node27 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 28> {typedef typename hrp2_14<FloatType>::Node28 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 29> {typedef typename hrp2_14<FloatType>::Node29 type;};
template <typename FloatType> struct Nodes < hrp2_14<FloatType>, 30> {typedef typename hrp2_14<FloatType>::Node30 type;};


} // closing namespace metapod

# ifdef _MSC_VER
#  pragma warning( pop )
# endif

#endif

